spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql6.sqlpub.com:3311/schoolwarehouse
    username: schoolwarehouse
    password: "GgiaxpLH6pk2WbF7"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  redis:
    host: redis-11227.crce264.ap-east-1-1.ec2.cloud.redislabs.com
    port: 11227
    password: "oLyyEhkXCydACkBn5pRQuNG5CIFueVSZ"
    database: 0
  mail:
    host: smtp.qq.com
    username: 196254331@qq.com
    password: bpdtjyehgbbfbjaj  # QQ?????????????
    port: 587
    default-encoding: UTF-8
    protocol: smtp # SMTP邮件协议
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
minio:
  endpoint: "http://47.118.31.5:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucket: "schoolwarehouse"

file:
  url: "https://47.118.31.5/api/file/download"
  pre-signature:
    secret-key : "MKYYRDzdKc23uM1VNqiNh4shzCGcfpH0"
    expire: 5 #过期时间 小时

server:
  port: 9191
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secretKey: "hVg1LcycfyZCJd0YPVujGKE1KtL7ntmHEHmXFAE10jcwPRopYiVAxQcaUxB4ZKFgDUCgBxY8ujMU4ZuNuhciAjPUmWG199ztEXwy"




knife4j:
  enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.basketball.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-enums-package: com.basketball.enums
